# Generated by Django 5.1.1 on 2025-02-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
    ]
