# Generated by Django 5.1.1 on 2025-02-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="unique_product_variant",
        ),
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="size_non_negative",
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={
                ("product", "brand", "size", "flavor"),
                ("product", "sku"),
            },
        ),
    ]
