# Generated by Django 5.1.1 on 2025-02-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productvariant_unique_product_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproductvariant",
            name="low_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="historicalproductvariant",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="low_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock",
        ),
    ]
