# Generated by Django 5.1.1 on 2025-02-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productvariant_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "size", "flavor")},
        ),
    ]
