# Generated by Django 5.1.1 on 2025-02-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_remove_historicalproductvariant_low_stock_threshold_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproductvariant",
            name="author",
        ),
        migrations.RemoveField(
            model_name="historicalproductvariant",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproductvariant",
            name="product",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="HistoricalProductVariant",
        ),
    ]
