# Generated by Django 5.1.1 on 2025-02-17 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="default", max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(default="default", max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(default="default", max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
