# Generated by Django 5.1.1 on 2025-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_category_alter_product_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["id", "name"],
                "verbose_name_plural": "Product categories",
            },
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The size of the product.",
                max_digits=10,
            ),
        ),
    ]
