# Generated by Django 5.1.1 on 2025-02-17 07:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_slug_productcategory_created_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Product categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="Use tags to add health benefits, Hair growth, etc.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
