# Generated by Django 5.1.1 on 2025-02-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is the productavailable for purchase?"
            ),
        ),
    ]
