# Generated by Django 5.1.1 on 2025-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvariantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product.",
                null=True,
                upload_to="product_variants/",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name="ProductVariantImage",
        ),
    ]
