# Generated by Django 5.1.1 on 2025-02-19 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvariant_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this product available for purchase?"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flavor", None), _negated=True),
                fields=("product", "size", "flavor"),
                name="unique_product_variant",
            ),
        ),
    ]
