# Generated by Django 5.1.1 on 2025-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to="inventory-api/product_categories/",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="flavor",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product.",
                null=True,
                upload_to="inventory-api/product_variants/",
            ),
        ),
    ]
