# Generated by Django 5.1.1 on 2025-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productcategory_image_alter_productvariant_flavor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product.",
                null=True,
                upload_to="inventory-api/products/",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product variant.",
                null=True,
                upload_to="inventory-api/product_variants/",
            ),
        ),
    ]
