# Generated by Django 5.1.1 on 2025-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_product_image_alter_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Stock Keeping Unit for inventory tracking.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
