# Generated by Django 5.1.1 on 2025-02-19 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productvariant_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="unique_product_variant",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="brand",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit for inventory tracking.",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flavor", None), _negated=True),
                fields=("product", "brand", "size", "flavor"),
                name="unique_product_variant",
            ),
        ),
    ]
