# Generated by Django 5.1.1 on 2025-02-19 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_remove_productvariant_unique_product_variant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Has this product been deleted?"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Is this product available for purchase?",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Stock Keeping Unit for inventory tracking.",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["slug"], name="products_pr_slug_d83465_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="products_pr_sku_dcab68_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_9d6315_idx"
            ),
        ),
    ]
