# Generated by Django 5.1.1 on 2025-02-19 15:55

from django.db import migrations, models

import core.products.utils


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0014_productvariant_is_deleted_alter_productvariant_brand_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.products.utils.product_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to=core.products.utils.product_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.products.utils.product_image_upload_path,
            ),
        ),
    ]
