# Generated by Django 5.1.1 on 2025-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_historicalproduct_historicalproductvariant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="An image of the product.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductvariant",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="An image of the category.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product.",
                null=True,
                upload_to="inventory-api/products/",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to="inventory-api/product_categories/",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to="inventory-api/product_categories/",
            ),
        ),
    ]
