# Generated by Django 5.1.1 on 2025-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_historicalproduct_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the product.",
                null=True,
                upload_to="products/",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An image of the category.",
                null=True,
                upload_to="variants/",
            ),
        ),
    ]
