# Generated by Django 5.1.1 on 2025-02-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="type",
            field=models.CharField(
                choices=[("STORAGE", "Storage"), ("SHOP", "Shop")],
                default="STORAGE",
                help_text="The type of warehouse.",
                max_length=20,
            ),
        ),
    ]
