# Generated by Django 5.1.1 on 2025-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0004_alter_warehouseuser_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
