# Generated by Django 5.1.1 on 2025-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0005_alter_warehouse_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PRIVATE",
                help_text="Determines if the warehouse is visible to the public.",
                max_length=20,
            ),
        ),
    ]
