# Generated by Django 5.1.1 on 2025-02-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0007_stockalert"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockalert",
            old_name="created_at",
            new_name="created",
        ),
    ]
