# Generated by Django 5.1.1 on 2025-02-23 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_historicalproduct_historicalproductvariant"),
        ("warehouses", "0008_rename_created_at_stockalert_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_quantity",
                    models.IntegerField(
                        help_text="Positive to add stock, negative to reduce stock."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGE", "Damaged"),
                            ("LOSS", "Lost"),
                            ("EXPIRY", "Expired"),
                            ("AUDIT_CORRECTION", "Audit Correction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="products.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counted_quantity",
                    models.PositiveIntegerField(
                        help_text="The quantity of stock counted during the audit."
                    ),
                ),
                (
                    "recorded_quantity",
                    models.PositiveIntegerField(
                        help_text="The expected quantity in the system before the audit."
                    ),
                ),
                (
                    "discrepancy",
                    models.IntegerField(
                        help_text="The difference between recorded and counted stock."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_audits",
                        to="products.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_audits",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
        ),
    ]
