# Generated by Django 5.1.1 on 2025-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0010_alter_stockadjustment_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockalert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
